apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sharmio-demo
  name: sharmio-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leader-election
  name: leader-election
  namespace: sharmio-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      automountServiceAccountToken: true
      serviceAccount: leader-election-sa
      containers:
      - image: docker.io/imoisharma/k8s-leader-election:v1
        name: leader-election
        args:
          - --lease-name=my-lease
        env:
          - name: POD_NAME
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
