apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sharmio-demo
  name: sharmio-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leader-election
    kubernetes.io/metadata.name: sharmio-demo
  name: leader-election
  namespace: sharmio-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
      kubernetes.io/metadata.name: sharmio-demo
  template:
    metadata:
      labels:
        app: leader-election
        kubernetes.io/metadata.name: sharmio-demo
    spec:
      automountServiceAccountToken: true
      serviceAccount: leader-election-sa
      containers:
      - image: docker.io/imoisharma/k8s-leader-election:v2
        name: leader-election
        args:
          - --lease-name=sharmio-lease
          - --lease-namespace=sharmio-demo
        env:
          - name: POD_NAME
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
